## 4.5 XGBoost(eXtra Gradient Boost)
### 4.5.1 XGBoost 설치

In [4]:
#pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import xgboost as xgb
from xgboost import XGBClassifier

### 4.5.2 위스콘신 유방암 예측

In [6]:
from xgboost import plot_importance
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [8]:
dataset = load_breast_cancer()
features = dataset.data
labels = dataset.target

In [9]:
cancer_df = pd.DataFrame(data=features, columns = dataset.feature_names)
cancer_df['target'] = labels
cancer_df.head()

mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

In [10]:
print(dataset.target_names)
print(cancer_df['target'].value_counts())

['malignant' 'benign']
1    357
0    212
Name: target, dtype: int64


양성: malignant(357)
음성: benign(212)

In [11]:
# cancer_df에서 feature용 DataFrame과 Label용 Series 객체 추출
# 맨 마지막 칼럼이 label

X_features = cancer_df.iloc[:,:-1]
y_label = cancer_df.iloc[:,-1]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X_features, y_label, test_size=0.2, random_state=156)

# 위에서 만든 X_train, y_train을 다시 쪼개서 90%는 학습과 10%는 검증용 데이터로 분리
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.1, random_state=156)

print(X_train.shape, X_test.shape)
print(X_tr.shape, X_val.shape)

(455, 30) (114, 30)
(409, 30) (46, 30)


In [13]:
dtr = xgb.DMatrix(data=X_tr, label=y_tr)
dval = xgb.DMatrix(data=X_val, label=y_val)
dtest = xgb.DMatrix(data=X_test, label=y_test)

In [15]:
params={'max_depth':3, 
        'eta':0.05,
        'objective': 'binary:logistic',
        'eval_metric':'logloss'}
num_rounds=400

In [16]:
# 학습 데이터 셋은 'train' 평가 데이터셋은 'eval'로 명기
eval_list = [(dtr, 'train'), (dval, 'eval')]

xgb_model = xgb.train(params = params, dtrain = dtr, num_boost_round = num_rounds, early_stopping_rounds=50, evals=eval_list)

[0]	train-logloss:0.650163	eval-logloss:0.661831
Multiple eval metrics have been passed: 'eval-logloss' will be used for early stopping.

Will train until eval-logloss hasn't improved in 50 rounds.
[1]	train-logloss:0.611313	eval-logloss:0.636086
[2]	train-logloss:0.575629	eval-logloss:0.611436
[3]	train-logloss:0.543102	eval-logloss:0.592036
[4]	train-logloss:0.513233	eval-logloss:0.573291
[5]	train-logloss:0.484475	eval-logloss:0.550371
[6]	train-logloss:0.457959	eval-logloss:0.529295
[7]	train-logloss:0.434357	eval-logloss:0.51534
[8]	train-logloss:0.411503	eval-logloss:0.497179
[9]	train-logloss:0.390274	eval-logloss:0.481542
[10]	train-logloss:0.371284	eval-logloss:0.469904
[11]	train-logloss:0.352541	eval-logloss:0.45474
[12]	train-logloss:0.335277	eval-logloss:0.442294
[13]	train-logloss:0.318925	eval-logloss:0.429608
[14]	train-logloss:0.304394	eval-logloss:0.42065
[15]	train-logloss:0.289996	eval-logloss:0.409577
[16]	train-logloss:0.276514	eval-logloss:0.398867
[17]	train-log

126번째 반복에서 eval-logloss가 0.25587로 가장 낮음

In [17]:
pred_probs = xgb_model.predict(dtest)
print('predict( ) 수행 결과값을 10개만 표시, 예측 확률 값으로 표시됨')
print(np.round(pred_probs[:10], 3))

# 예측 확률이 0.5보다 크면 1, 그렇지 않으면 0으로 예측 값 결정하여 List 객체인 preds에 저장
preds = [ 1 if x >0.5 else 0 for x in pred_probs]
print('예측값 10개만 표시: ', preds[:10])

predict( ) 수행 결과값을 10개만 표시, 예측 확률 값으로 표시됨
[0.845 0.008 0.68  0.081 0.975 0.999 0.998 0.998 0.996 0.001]
예측값 10개만 표시:  [1, 0, 1, 0, 1, 1, 1, 1, 1, 0]


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score

def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

In [19]:
get_clf_eval(y_test , preds, pred_probs)

오차 행렬
[[34  3]
 [ 2 75]]
정확도: 0.9561, 정밀도: 0.9615, 재현율: 0.9740,    F1: 0.9677, AUC:0.9937


### 4.5.3 사이킷런 래퍼 XGBoost 개요 및 적용

In [21]:
from xgboost import XGBClassifier

xgb_wrapper = XGBClassifier(n_estimators=400, learning_Rate=0.05, max_depth=3, eval_metric='logloss')
xgb_wrapper.fit(X_train, y_train, verbose=True)
w_preds = xgb_wrapper.predict(X_test)
w_preds_proba = xgb_wrapper.predict_proba(X_test)[:,1]

In [23]:
get_clf_eval(y_test, w_preds, w_preds_proba)

오차 행렬
[[35  2]
 [ 1 76]]
정확도: 0.9737, 정밀도: 0.9744, 재현율: 0.9870,    F1: 0.9806, AUC:0.9951


In [24]:
xgb_wrapper = XGBClassifier(n_estimators=400, learning_Rate=0.05, max_depth=3)
evals = [(X_tr, y_tr), (X_val, y_val)]
xgb_wrapper.fit(X_tr, y_tr, early_stopping_rounds=50, eval_metric = 'logloss', eval_set=evals, verbose=True)
ws50_preds = xgb_wrapper.predict(X_test)
ws50_pred_proba=xgb_wrapper.predict_proba(X_test)[:,1]

[0]	validation_0-logloss:0.609309	validation_1-logloss:0.632341
Multiple eval metrics have been passed: 'validation_1-logloss' will be used for early stopping.

Will train until validation_1-logloss hasn't improved in 50 rounds.
[1]	validation_0-logloss:0.54033	validation_1-logloss:0.591335
[2]	validation_0-logloss:0.482451	validation_1-logloss:0.555478
[3]	validation_0-logloss:0.43082	validation_1-logloss:0.514399
[4]	validation_0-logloss:0.386624	validation_1-logloss:0.481856
[5]	validation_0-logloss:0.350313	validation_1-logloss:0.460872
[6]	validation_0-logloss:0.316809	validation_1-logloss:0.436703
[7]	validation_0-logloss:0.287157	validation_1-logloss:0.412904
[8]	validation_0-logloss:0.262035	validation_1-logloss:0.392834
[9]	validation_0-logloss:0.239122	validation_1-logloss:0.378621
[10]	validation_0-logloss:0.218812	validation_1-logloss:0.365379
[11]	validation_0-logloss:0.200896	validation_1-logloss:0.351744
[12]	validation_0-logloss:0.184499	validation_1-logloss:0.339446
[1

In [25]:
get_clf_eval(y_test, ws50_preds, ws50_pred_proba)

오차 행렬
[[34  3]
 [ 3 74]]
정확도: 0.9474, 정밀도: 0.9610, 재현율: 0.9610,    F1: 0.9610, AUC:0.9940


In [26]:
# early_stop 10으로 재학습
xgb_wrapper.fit(X_tr, y_tr, early_stopping_rounds=10, eval_metric = 'logloss', eval_set=evals, verbose=True)
ws10_preds = xgb_wrapper.predict(X_test)
ws10_pred_proba=xgb_wrapper.predict_proba(X_test)[:,1]
get_clf_eval(y_test, ws10_preds, ws10_pred_proba)

[0]	validation_0-logloss:0.609309	validation_1-logloss:0.632341
Multiple eval metrics have been passed: 'validation_1-logloss' will be used for early stopping.

Will train until validation_1-logloss hasn't improved in 10 rounds.
[1]	validation_0-logloss:0.54033	validation_1-logloss:0.591335
[2]	validation_0-logloss:0.482451	validation_1-logloss:0.555478
[3]	validation_0-logloss:0.43082	validation_1-logloss:0.514399
[4]	validation_0-logloss:0.386624	validation_1-logloss:0.481856
[5]	validation_0-logloss:0.350313	validation_1-logloss:0.460872
[6]	validation_0-logloss:0.316809	validation_1-logloss:0.436703
[7]	validation_0-logloss:0.287157	validation_1-logloss:0.412904
[8]	validation_0-logloss:0.262035	validation_1-logloss:0.392834
[9]	validation_0-logloss:0.239122	validation_1-logloss:0.378621
[10]	validation_0-logloss:0.218812	validation_1-logloss:0.365379
[11]	validation_0-logloss:0.200896	validation_1-logloss:0.351744
[12]	validation_0-logloss:0.184499	validation_1-logloss:0.339446
[1